### ISSUE TITLE
Option For Collections That Include Digital Copies Such As Vudu, Movies Anywhere and so on

### ISSUE THREAD

**Issue by kcook85** [KevinDeery/Cinema-Box-Collector#10]
Option For Collections That Include Digital Copies Such As Vudu, Movies Anywhere and so on, i have a large Digital and physical movie collection and to be able to list them all in the app  based on type would be awesome

**Comment by KevinDeery** [comment]
@kcook85 
are you asking if the app can point your account for these services and pull down the media list or are you asking for a means of setting the type like digital to VUDU etc so you can filter on this ?

**Comment by kcook85** [comment]
Yes Sorry, to filter what movies i have that are digital vs my physical

**Comment by KevinDeery** [comment]
@kcook85 

I have implemented this functionality and will be pushing this out tonight , id bee grateful of your feedback 

1. Manually adding movies
   A provider option is provided now
   [https://drive.google.com/file/d/1LJyHkg8ub48Cs9gGxobCvxdoIqSPieXc/view?usp=sharing](url)

2. Movie Details 
   Properties tab allows you to set a provider 
   [https://drive.google.com/file/d/14dABe_wBHB3_buPNL1VR_lw860BCP45w/view?usp=sharing](url)

3. Movie Collection
    You can not filter by providers
    [https://drive.google.com/file/d/1zUo6cf2ecSP4RXgAk6xlP3QHxXm8nqfu/view?usp=sharing](url)
