### ISSUE TITLE
Forgot password problem

### ISSUE THREAD

**Issue by kcook85** [KevinDeery/Cinema-Box-Collector#16]
Make it so the system remembers what we used for our security question as it's very hard to remember what I used as my security question so I cannot request a password reset otherwise and can't login to my account using the app

**Comment by KevinDeery** [comment]
Hi, I'll send you the information for your security question.

I cannot send you your password because it's encrypted

Kevin

**Comment by KevinDeery** [comment]
Maybe I misunderstood , when you enter your email, the application will
return your security question.

Im assuming you cannot remember the answer to your question

Kevin

**Comment by KevinDeery** [comment]
Can you email me directly at cinemaboxhelp@gmail.com and ill send you your security answer. When you enter this , it will send you a temporary password with will allow you to reset your old password.

Thanks 
Kevin
